# Basic Metadata
title: Jun Wang
description: Personal Website
theme: just-the-docs
url: https://junwang0510.github.io

# Aux links for the upper right navigation
aux_links:
  "Resume":
  - "https://github.com/junwang0510/Resume/blob/main/Wang%2CJun.pdf"
  "LinkedIn":
  - "https://www.linkedin.com/in/junwang0510/"
  "GitHub":
  - "https://github.com/junwang0510"
  "Instagram":
  - "https://www.instagram.com/junie_wangy/"
aux_links_new_tab: true

# Footer Content
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2023 Jun Wang. Distributed by an <a href=\"https://github.com/junwang0510/junwang0510.github.io/blob/main/LICENSE\">MIT license.</a>"

# Favicon
favicon_ico: "Images/magic_favicon.PNG"