title: Jun Wang
description: Personal Website
theme: just-the-docs

url: https://junwang0510.github.io

aux_links:
  "LinkedIn":
  - "https://www.linkedin.com/in/junwang0510/"
  "GitHub":
  - "https://github.com/junwang0510"
  "Insta":
  - "https://www.instagram.com/junie_wangy/"
  